# Generated by Django 5.2.1 on 2025-05-28 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_books', '0002_alter_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(help_text='Cash flow status name', max_length=30, unique=True),
        ),
    ]
