# Generated by Django 5.2.1 on 2025-05-28 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_books', '0003_alter_status_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Clash flow category name', max_length=30, unique=True),
        ),
    ]
