# Generated by Django 5.2.1 on 2025-05-28 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_books', '0005_subcategory_unique_subcategory_per_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.ForeignKey(default=0, help_text='Parent type', on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='reference_books.type'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('name', 'type'), name='unique_category_per_type'),
        ),
    ]
