# Generated by Django 5.2.1 on 2025-05-29 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reference_books', '0006_category_type_category_unique_category_per_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name_plural': 'Statuses'},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name_plural': 'Types'},
        ),
    ]
