# Generated by Django 5.2.1 on 2025-05-30 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_books', '0007_alter_category_options_alter_status_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(db_index=True, help_text='Clash flow subcategory name', max_length=30),
        ),
    ]
