# Generated by Django 5.2.1 on 2025-05-29 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reference_books', '0007_alter_category_options_alter_status_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_now_add=True, help_text='The date when the cash flow record was created.', verbose_name='Creation date')),
                ('amount', models.DecimalField(decimal_places=2, help_text='The amount of funds in rubles', max_digits=8)),
                ('comment', models.TextField(blank=True, help_text='Comment on the entry in free form.', null=True)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference_books.status')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference_books.subcategory')),
            ],
            options={
                'verbose_name': 'Cash Flow',
                'verbose_name_plural': 'Cash Flows',
                'ordering': ('creation_date',),
            },
        ),
    ]
