# Generated by Django 5.2.1 on 2025-05-30 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_flows', '0002_alter_cashflow_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflow',
            name='creation_date',
            field=models.DateField(db_index=True, help_text='The date when the cash flow record was created. If you do not specify a value or specify a date from the future, the current date will be set.', null=True, verbose_name='Creation date'),
        ),
    ]
